[package]
name = "lsp_rs"
version = "0.1.0"
authors = ["Jacob Smith <jacob101607@yahoo.com>"]

[dependencies]
erased-serde = "0.1.3"
futures = "0.1"
languageserver-types = "0.6.1"
log = "0.3.6"
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
tokio-core = "0.1"